# SPDX-FileCopyrightText: ©2025 franklin <smoooth.y62wj@passmail.net>
#
# SPDX-License-Identifier: MIT

ACLOCAL_AMFLAGS = -I config/m4
CLOCAL_AMFLAGS = -I config/m4

clean:
    rm -rf config/ configure configure~  autom4te.cache/  aclocal.m4
    rm-rf *.egg-info
    find . -name '*.pyc' | xargs rm -rf
    find . -name '__pycache__' | xargs rm -rf