# SPDX-FileCopyrightText: 2021-2025 franklin <smoooth.y62wj@passmail.net>
#
# SPDX-License-Identifier: MIT

server {
    listen 80;
    listen [::]:80;
    server_name bitsmasher.net www.bitsmasher.net; # Configured for both TLD and FQDN
    return 301 https://$host$request_uri; # Redirect all HTTP to HTTPS
}

server {
    listen 443 ssl;
    #listen [::]:443 ssl; # Uncommented for IPv6 support

    server_name bitsmasher.net www.bitsmasher.net; # Configured for both TLD and FQDN
    ssl_certificate /etc/letsencrypt/live/www.bitsmasher.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.bitsmasher.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'HIGH:!aNULL:!MD5';
    access_log /var/log/nginx/bitsmasher.net.access.log;
    error_log /var/log/nginx/bitsmasher.net.error.log error;

    location /.well-known {
        alias /home/franklin/workspace/website/static/www/.well-known;
        allow all; 
    }

    location / {
        root /home/franklin/workspace/website/static/www;
        index index.html;
        try_files $uri $uri/ =404;  # This line allows for proper handling of existing files
    }
}
