# SPDX-FileCopyrightText: 2021-2025 franklin <smoooth.y62wj@passmail.net>
#
# SPDX-License-Identifier: MIT

# Managed by ansible: /etc/nginx/nginx.conf

server {
    listen 80;
    listen [::]:80;
    server_name bitsmasher.net; # Specific server name
    return 301 https://$host$request_uri; # Redirect all HTTP to HTTPS
}

# HTTPS Server (Port 443) for www.bitsmasher.net
server {
    listen 443 ssl;
    listen [::]:443 ssl ipv6only=on;

    server_name bitsmasher.net;

    # SSL Certificates (Managed by Certbot)
    ssl_certificate /etc/letsencrypt/live/www.bitsmasher.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.bitsmasher.net/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf; # Recommended security settings
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # SSL Settings
    # ssl_protocols TLSv1.2 TLSv1.3;                          # Specify protocols
    # ssl_ciphers 'HIGH:!aNULL:!MD5';                          # Specify ciphers

    # Logging (Optional, but good practice)
    access_log /var/log/nginx/www.bitsmasher.net.access.log;
    error_log /var/log/nginx/www.bitsmasher.net.error.log error; # Reduced log noise

    # Reverse Proxy Configuration
    location / {
        proxy_pass http://178.62.60.55:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; # Pass the original protocol
        proxy_set_header X-Forwarded-Host $host; # Ensure correct handling of the original host
        proxy_http_version 1.1; # Enable HTTP/1.1 for websocket support
        proxy_set_header Upgrade $http_upgrade; # For WebSocket support
        
        # CORS Configuration
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*'; # Adjust this based on security policies
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }
}

# Default Catch-All (Optional, Recommended for Security)
server {
    listen 80 default_server; # Captures unmatched HTTP requests
    listen [::]:80 default_server;

    server_name _; # Catch-all server name
    return 301 https://bitsmasher.net; # Redirect to the main site
}

