version: '3'
services:
  bitsmasher:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: bitsmasher.net
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  dev_bitsmasher:
    hostname: bitsmasher.net
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: dev_bitsmasher
    ports:
      - "5000:5000"
    volumes:
- .:/app
