# SPDX-FileCopyrightText: 2021-2025 franklin <smoooth.y62wj@passmail.net>
#
# SPDX-License-Identifier: MIT

server {
    listen 80;
    listen [::]:80;
    server_name bitsmasher.net www.bitsmasher.net; # Configured for both TLD and FQDN
    return 301 https://$host$request_uri; # Redirect all HTTP to HTTPS
}

server {
    listen 443 ssl;
    server_name bitsmasher.net www.bitsmasher.net;

    ssl_certificate /etc/letsencrypt/live/www.bitsmasher.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.bitsmasher.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'HIGH:!aNULL:!MD5';

    access_log /var/log/nginx/bitsmasher.net.access.log;
    error_log /var/log/nginx/bitsmasher.net.error.log error;

    location /.well-known {
        alias /mnt/lab_franklin_1/workspace/website/static/www/.well-known;
        allow all;
        autoindex on;
        autoindex_exact_size off;
        index off;
    }

    location /.well-known/nostr.json {
        add_header Access-Control-Allow-Origin *;
        add_header Content-Type application/json;
    }

    location /images/ {
        allow all;
        autoindex on;
        autoindex_exact_size off;
    }

    location /research/ {
        allow all;
	index index.html index.json;
        autoindex on;
        autoindex_exact_size off;
    }

    location /teaching/ {
        allow all;
        autoindex on;
        autoindex_exact_size off;
    }


    location /manual/ {
       allow all;
       autoindex on;
       autoindex_exact_size off;
    }

    location / {
        root /mnt/lab_franklin_1/workspace/website/static/www;
	index index.html index.json;

        # CORS Headers
        add_header 'Access-Control-Allow-Origin' '*' always;  # Adjust based on security policies
	# add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type' always;

        # Handle OPTIONS requests
        if ($request_method = 'OPTIONS') {
            return 204;
        }

        try_files $uri $uri/ =404;
    }
}

