server {
    listen 80 default_server;
    # listen [::]:80 default_server;
    root /usr/share/nginx/html;  # This 'root' combines with the location path
    server_name snowy.lab.bitsmasher.net;
    
    location ~ /\.well-known {
    allow all;
    }

    location / {
        proxy_pass http://localhost:8080;
    }
}