# SPDX-FileCopyrightText: 2021-2025 franklin <smoooth.y62wj@passmail.net>
#
# SPDX-License-Identifier: MIT

server {
    listen 80;
    listen [::]:80;
    server_name chonk.lab.bitsmasher.net; # Specific server name
    return 301 https://$host$request_uri; # Redirect all HTTP to HTTPS
}

server {
    listen 443 ssl;
    # listen [::]:443 ssl ipv6only=on;

    server_name chonk.lab.bitsmasher.net;
    ssl_certificate /etc/letsencrypt/live/chonk.lab.bitsmasher.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chonk.lab.bitsmasher.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'HIGH:!aNULL:!MD5';
    access_log /var/log/nginx/chonk.lab.bitsmasher.net.access.log;
    error_log /var/log/nginx/chonk.lab.bitsmasher.net.error.log error;

  location /minecraft {
        # Enable directory listing
        autoindex on;
 
        # Optional: Show human-readable file sizes instead of bytes
        autoindex_exact_size off;
 
        # Optional: Use local server time for timestamps
        autoindex_localtime on;
 
        # Optional: Disable index files to force listing (even if index.html exists)
        index off;
}
}
